version: '3'

dotenv:
  - "{{.ENV_FILE}}"
vars:
  USER: isucon
  BIN_NAME: isupipe-bin
  BUILD_DIR: /home/isucon/webapp/go
  SERVICE_NAME: isupipe-go.service
  ENV_FILE: env.sh

  # GIT
  GIT_REPOSIROTY: git@github.com/com3-jp/istmpl
  GIT_DB_PATH: $HOME/$SERVER_ID/etc/mysql
  GIT_NGINX_PATH: $HOME/$SERVER_ID/etc/nginx
  GIT_SERVICE_PATH: $HOME/$SERVER_ID/etc/{{.SERVICE_NAME}}
  GIT_ENV_FILE: $HOME/$SERVER_ID/{{.ENV_FILE}}

  # ALP
  ALP_PATH: $HOME/bin/alp
  ALP_CONFIG: $HOME/tools/alp/config.yml

  # Netdata
  NETDATA_PATH: /etc/netdata
  NETDATA_WEBROOT_PATH: /var/lib/netdata/www/

  # DB
  DB_PATH: /etc/mysql
  DB_CONFIG: /etc/mysql/my.cnf
  DB_SLOW_LOG: /var/log/mysql/mysql-slow.log
  DB_SLOW_QUERY_TIME: 1
  DB_USER: root
  DB_PASSWORD: password

  # NGINX
  NGINX_PATH: /etc/nginx
  NGINX_CONFIG: /etc/nginx/nginx.conf
  NGINX_ACCESS_LOG: /var/log/nginx/access.log

  # SYSTEMD
  SYSTEMD_PATH: /etc/systemd/system

  # SYSCTD
  SYSCTD_PATH: /etc/sysctl.d/
  SYSCTD_NAME: isu.conf

  # LIMITS
  LIMITS_PATH: /etc/security/limits.d/
  LIMITS_NAME: limits.conf

tasks:
  db:
    desc: "DB CLI"
    cmds:
      - mysql -u {{.DB_USER}} -p{{.DB_PASSWORD}}
  show-db-variables:
    desc: "Show DB variables"
    cmds:
      - mysql -u {{.DB_USER}} -p{{.DB_PASSWORD}} -e "SHOW VARIABLES"

  pt-query-digest:
    desc: "Analyze slow query log"
    cmds:
      - sudo pt-query-digest {{.DB_SLOW_LOG}} | cut -c 1000

  alp:
    desc: "Analyze access log"
    cmds:
      - sudo {{.ALP_PATH}} ltsv --file={{.NGINX_ACCESS_LOG}} --config={{.ALP_CONFIG}}

  restart:
    desc: "Restart services"
    cmds:
      - sudo systemctl daemon-reload
      - sudo systemctl restart {{.SERVICE_NAME}}
      - sudo systemctl restart mysql
      - sudo systemctl restart nginx
      - sudo systemctl restart netdata

  status:
    desc: "Check status of services"
    cmds:
      - sudo systemctl status {{.SERVICE_NAME}}
      - sudo systemctl status mysql
      - sudo systemctl status nginx
      - sudo systemctl status netdata

  deploy-conf:
    desc: "Deploy configuration files (DB, Nginx, Service, env.sh)"
    cmds:
      - task: check-server-id
      - task: deploy-db-conf
      - task: deploy-nginx-conf
      - task: deploy-service-conf
      - task: deploy-env-file
  
  deploy-db-conf:
    preconditions:
      - task: check-server-id
    cmds:
      - sudo cp -r {{.GIT_DB_PATH}}/* {{.DB_PATH}}
  
  deploy-nginx-conf:
    preconditions:
      - task: check-server-id
    cmds:
      - sudo cp -r {{.GIT_NGINX_PATH}}/* {{.NGINX_PATH}}
  
  deploy-service-conf:
    preconditions:
      - task: check-server-id
    cmds:
      - sudo cp -r {{.GIT_SERVICE_PATH}}/* {{.SYSTEMD_PATH}}/{{.SERVICE_NAME}}
  
  deploy-env-file:
    preconditions:
      - task: check-server-id
    cmds:
      - cp {{.GIT_ENV_FILE}} $HOME/

  get-conf:
    desc: "Get configuration files (DB, Nginx, Service, env.sh)"
    cmds:
      - task: check-server-id
      - task: get-db-conf
      - task: get-nginx-conf
      - task: get-service-conf
      - task: get-env-file

  get-db-conf:
    preconditions:
      - task: check-server-id
    cmds:
      - mkdir -p {{.GIT_DB_PATH}}
      - sudo cp -r {{.DB_PATH}}/* {{.GIT_DB_PATH}}
      - sudo chown -R {{.USER}}:{{.USER}} {{.GIT_DB_PATH}}

  get-nginx-conf:
    preconditions:
      - task: check-server-id
    cmds:
      - mkdir -p {{.GIT_NGINX_PATH}}
      - sudo cp -r {{.NGINX_PATH}}/* {{.GIT_NGINX_PATH}}
      - sudo chown -R {{.USER}}:{{.USER}} {{.GIT_NGINX_PATH}}
  
  get-service-conf:
    preconditions:
      - task: check-server-id
    cmds:
      - mkdir -p {{.GIT_SERVICE_PATH}}
      - sudo cp -r {{.SYSTEMD_PATH}}/{{.SERVICE_NAME}} {{.GIT_SERVICE_PATH}}
      - sudo chown -R {{.USER}}:{{.USER}} {{.GIT_SERVICE_PATH}}

  get-env-file:
    preconditions:
      - task: check-server-id
    cmds:
      - cp {{.ENV_FILE}} $HOME/$SERVER_ID/
      - sudo chown -R {{.USER}}:{{.USER}} $HOME/$SERVER_ID

  # Check for precondition
  check-server-id:
    preconditions:
      - sh: '[ $SERVER_ID != "" ]'
        msg: Env SERVER_ID is unset
    cmd: echo "SERVER_ID = $SERVER_ID"
